# Change these first
owner: santaclaraca # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: City of Santa Clara
    url: https://www.santaclaraca.gov
    maxResponseTime: 10000
  - name: Admin
    url: https://www.santaclaraca.gov/Admin 
    maxResponseTime: 10000
  - name: E-mails
    url: https://admin.govdelivery.com
    maxResponseTime: 10000
  - name: Silicon Valley Animal Control Authority
    url: https://www.svaca.com
    maxResponseTime: 10000
  - name: Silicon Valley Power
    url: https://www.siliconvalleypower.com
    maxResponseTime: 10000
  - name: Fiber Connect
    url: https://www.svpfiber.com
    maxResponseTime: 10000
  - name: Santa Clara City Library
    url: https://www.sclibrary.org
    maxResponseTime: 10000
  - name: Legistar
    url: https://santaclara.legistar.com/
    maxResponseTime: 10000
  - name: Accela
    url: https://aca-prod.accela.com/santaclara
    maxResponseTime: 10000
  - name: Cludo
    url: https://my.cludo.com
    maxResponseTime: 10000
  - name: Mark43
    url: https://mark43.com
    maxResponseTime: 10000
  - name: SiteImprove
    url: https://id.siteimprove.com/Account/Login
    maxResponseTime: 10000
  - name: PeopleSoft
    url: https://ESS.SantaClaraCA.gov
    maxResponseTime: 10000
  - name: Harris Customer Connect
    method: GET
    url: https://mua/CC/connect/authentication/AdminLogin.xml
    __dangerous__insecure: true
  - name: FTB
    method: GET
    url: https://swift.ftb.ca.gov
    __dangerous__insecure: true
  - name: ArcGIS
    url: https://www.arcgis.com/
    maxResponseTime: 10000
  - name: Site Core
    url: https://www.corebt.com/
    maxResponseTime: 10000
  - name: HDl
    url: https://www.hdlcompanies.com/
    maxResponseTime: 10000
  - name: Metaviewer
    url: https://www.metaviewer.com/
    maxResponseTime: 10000
  - name: Tiburon RMS
    url: https://prioritydispatch.net/tiburon-inc/
    maxResponseTime: 10000
  - name: CAD Zetron
    url: https://portal.zetron.com/
    maxResponseTime: 10000
  - name: ITPipes
    url: https://fortworthsanitary.itpipes.com/
    maxResponseTime: 10000
  - name: Nice Systems
    url: https://login.incontact.com/
    maxResponseTime: 10000
  - name: IntelliVUE
    url: https://intellicloud2.intellinetics.com/intelliCloudVUE/
    maxResponseTime: 10000
  - name: Tech Logic
    url: https://www.tech-logic.com/
    maxResponseTime: 10000
  - name: Faster Fleet Management
    url: https://fasterasset.com/
    maxResponseTime: 10000
  - name: Linkup
    url: https://linkup.com/
    maxResponseTime: 10000
  - name: C-Cure 9000
    url: https://www.swhouse.com
    maxResponseTime: 10000
  - name: Imagetrend Elite Rescue (Fire & EMS)
    url: https://www.imagetrend.com/
    maxResponseTime: 10000
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "CSC websites status dashboard"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
